Update build-and-upload.yml

diff --git a/.github/workflows/build-and-upload.yml b/.github/workflows/build-and-upload.yml
--- a/.github/workflows/build-and-upload.yml
+++ b/.github/workflows/build-and-upload.yml
@@ -224,7 +224,11 @@ jobs:
         else
           git log --pretty=format:"* %s" ${TAG}^..${TAG} > extracted.txt || echo "See release notes: https://github.com/mhx/dwarfs/releases/tag/$TAG" > extracted.txt
         fi
-        END_CHANGELOG="EOF_${TAG}_CHANGELOG"
+        END_CHANGELOG="END_CHANGELOG_$(uuidgen 2>/dev/null || date +%s%N)"
+        if grep -q "$END_CHANGELOG" extracted.txt; then
+          echo "Error: Delimiter $END_CHANGELOG found in changelog output!" >&2
+          exit 1
+        fi
         {
           echo "notes<<$END_CHANGELOG"
           cat extracted.txt
@@ -246,7 +250,11 @@ jobs:
             --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
             --default-key "${{ steps.import_gpg.outputs.keyid }}" \
             --output checksums.txt.asc --detach-sign checksums.txt
-        END_CHECKSUMS="EOF_${TAG}_CHECKSUMS"
+        END_CHECKSUMS="END_CHECKSUMS_$(uuidgen 2>/dev/null || date +%s%N)"
+        if grep -q "$END_HECKSUMS" extracted.txt; then
+          echo "Error: Delimiter $END_CHECKSUMS found in checksum output!" >&2
+          exit 1
+        fi
          {
           echo "checksums<<$END_CHECKSUMS"
           cat checksums.txt
